spring:
  datasource:
    url: jdbc:mysql://localhost:3307/userservice?createDatabaseIfNotExist=true&
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



